
package finaleprojdonmatrix;

import java.awt.Button;
import java.awt.Component;
import java.awt.Frame;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.TimerTask;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
/**
 *
 * @author proxc
 */
public class Home17 extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public Home17() {
        con = javacon.ConnecrDb();
        initComponents();
   
    }
int xx,xy;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_login = new java.awt.Button();
        lbl_close = new javax.swing.JLabel();
        txt_pwd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_login1 = new java.awt.Button();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        loader = new javax.swing.JPanel();
        img_loader = new javax.swing.JLabel();
        lbl_loader = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new java.awt.CardLayout());

        login.setBackground(new java.awt.Color(0, 0, 0));
        login.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginMouseDragged(evt);
            }
        });
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginMousePressed(evt);
            }
        });
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home17/images/GRAYSMALL70X40.png"))); // NOI18N
        login.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 70, 80));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("DonMaTrix");
        login.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("<html> <br>© 2017 DonMaTrix.  All rights reserved</br> <br>  This project is not for sale and for project purpose only. </brr </html><br>  © 2017 DonMaTrix.  All rights reserved. </brr </html>");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        login.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 252, -1));

        txt_email.setBackground(new java.awt.Color(238, 238, 238));
        txt_email.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_email.setForeground(new java.awt.Color(0, 0, 0));
        txt_email.setText("Username or ID No.");
        txt_email.setBorder(null);
        txt_email.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emailFocusGained(evt);
            }
        });
        login.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 302, 50));

        jSeparator1.setBackground(new java.awt.Color(41, 168, 73));
        jSeparator1.setForeground(new java.awt.Color(41, 168, 73));
        login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 302, 10));

        jSeparator2.setBackground(new java.awt.Color(41, 168, 73));
        jSeparator2.setForeground(new java.awt.Color(41, 168, 73));
        login.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 302, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home17/images/lock-icon.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home17/images/user na pud.png"))); // NOI18N
        login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 50, 50));

        btn_login.setBackground(new java.awt.Color(51, 102, 255));
        btn_login.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setLabel("Login");
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_loginMouseExited(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        login.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 97, 35));

        lbl_close.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lbl_close.setForeground(new java.awt.Color(255, 255, 255));
        lbl_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_close.setText("X");
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_closeMousePressed(evt);
            }
        });
        login.add(lbl_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 27, -1));

        txt_pwd.setBackground(new java.awt.Color(238, 238, 238));
        txt_pwd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_pwd.setForeground(new java.awt.Color(0, 0, 0));
        txt_pwd.setText("jPasswordField1");
        txt_pwd.setBorder(null);
        txt_pwd.setCaretColor(new java.awt.Color(204, 204, 255));
        txt_pwd.setSelectedTextColor(new java.awt.Color(153, 153, 153));
        txt_pwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_pwdFocusGained(evt);
            }
        });
        login.add(txt_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 302, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home17/images/try3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 400, 160));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Login as:");
        login.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 80, 30));

        btn_login1.setActionCommand("Signup");
        btn_login1.setBackground(new java.awt.Color(51, 102, 255));
        btn_login1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_login1.setForeground(new java.awt.Color(255, 255, 255));
        btn_login1.setLabel("Sign up");
        btn_login1.setName(""); // NOI18N
        btn_login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login1ActionPerformed(evt);
            }
        });
        login.add(btn_login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 97, 35));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Teacher");
        login.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 90, 18));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Student");
        login.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 90, 17));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home17/images/homeback.png"))); // NOI18N
        jLabel4.setToolTipText("");
        login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 600));

        jPanel1.add(login, "card2");

        loader.setBackground(new java.awt.Color(0, 0, 0));
        loader.setMinimumSize(new java.awt.Dimension(640, 600));
        loader.setPreferredSize(new java.awt.Dimension(640, 600));
        loader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img_loader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home17/images/loadingcube.gif"))); // NOI18N
        loader.add(img_loader, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 420, 300));

        lbl_loader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_loader.setForeground(new java.awt.Color(41, 168, 73));
        lbl_loader.setText("Loggin in....");
        loader.add(lbl_loader, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home17/images/BackGround.png"))); // NOI18N
        loader.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));

        jPanel1.add(loader, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
         
    private void loginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_loginMousePressed

    private void loginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_loginMouseDragged

    private void btn_login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login1ActionPerformed
            if(jRadioButton1.isSelected()){
                new Regform().show();
                dispose();
            }
            else{
                new Regform1().show();
                dispose();
            }  
    }//GEN-LAST:event_btn_login1ActionPerformed
   
           
    private void txt_pwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_pwdFocusGained
        txt_pwd.setText("");
    }//GEN-LAST:event_txt_pwdFocusGained

    private void lbl_closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMousePressed
        System.exit(0);
    }//GEN-LAST:event_lbl_closeMousePressed
   
    private void txt_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusGained
        txt_email.setText("");
    }//GEN-LAST:event_txt_emailFocusGained

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        try{
            String sql;
            if(jRadioButton1.isSelected()){
                sql = "Select * from Dbl where username = ? and pass = ?";
                pst = con.prepareStatement(sql);
                pst.setString(1,txt_email.getText());
                pst.setString(2, txt_pwd.getText());
                pst.execute();
                rs =  pst.executeQuery();
                 File newFile = new File("C:\\datab\\data.txt");
                try {
                    newFile.createNewFile();
                } catch (IOException ex) {
                    Logger.getLogger(Home17.class.getName()).log(Level.SEVERE, null, ex);
                }
                 try {
                     FileWriter filew = new FileWriter(newFile);
                     BufferedWriter buffw = new BufferedWriter(filew);
                     buffw.write(txt_email.getText());
                     buffw.close();
                     System.out.print("copy");
                  } catch (IOException ex) {
                      Logger.getLogger(Home17.class.getName()).log(Level.SEVERE, null, ex);
                 }
                if(rs.next()){
                    loader.show();
                    login.hide();
                    new java.util.Timer().schedule(new TimerTask() {
                        @Override
                        public void run() {
                            System.out.println("Success");
                            menu ta = new menu();
                            ta.setVisible(true);
                            ta.pack();
                            ta.setLocationRelativeTo(null);
                            //also validate -

                            dispose();
                        }
                    },1000*5);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Username and Password doesn't match");
                }
            }
            else if(jRadioButton2.isSelected()){
                sql = "select * from Dba where Idnom = ? and pass = ?";
                pst = con.prepareStatement(sql);
                pst.setString(1, txt_email.getText());
                pst.setString(2, txt_pwd.getText());
                pst.execute();
                rs =  pst.executeQuery();
                File newFile = new File("C:\\datab\\data.txt");
                try {
                    newFile.createNewFile();
                } catch (IOException ex) {
                    Logger.getLogger(Home17.class.getName()).log(Level.SEVERE, null, ex);
                }
                 try {
                     FileWriter filew = new FileWriter(newFile);
                     BufferedWriter buffw = new BufferedWriter(filew);
                     buffw.write(txt_email.getText());
                     buffw.close();
                     System.out.print("copy");
                  } catch (IOException ex) {
                      Logger.getLogger(Home17.class.getName()).log(Level.SEVERE, null, ex);
                 }
                if(rs.next()){
                    loader.show();
                    login.hide();
                    new java.util.Timer().schedule(new TimerTask() {
                        @Override
                        public void run() {
                            System.out.println("Success");
                            viewstud ta = new viewstud();
                            ta.setVisible(true);
                            ta.pack();
                            ta.setLocationRelativeTo(null);
                            //also validate -
                            loader.show();
                            login.hide();
                            dispose();
                        }

                    },1000*5);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Username, Password or Log-in Type Doesn't Match");
                }

            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
          xx = evt.getX();
          xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void btn_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseEntered
        setColor(jPanel1);
    }//GEN-LAST:event_btn_loginMouseEntered

    private void btn_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseExited
        resetColor(jPanel1);
    }//GEN-LAST:event_btn_loginMouseExited
  
   public void setColor(JPanel panel)
   {
     panel.setBackground(new java.awt.Color(0,51,153));
   }
 
 public void resetColor(JPanel panel)
 {
    panel.setBackground(new java.awt.Color(51,102,255));
 }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home17().setVisible(true);
                new Home17().pack();            
            }
        });
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_login;
    private java.awt.Button btn_login1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel img_loader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_loader;
    private javax.swing.JPanel loader;
    private javax.swing.JPanel login;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txt_pwd;
    // End of variables declaration//GEN-END:variables
}
