/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finaleprojdonmatrix;

import java.io.BufferedReader;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author asdqwr
 */
public class seatplanstud extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public seatplanstud() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
         con = javacon.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSC = new javax.swing.JTextField();
        txtSN = new javax.swing.JTextField();
        txtSeatNumber = new javax.swing.JTextField();
        txtST = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(570, 270));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setText("Student Subject Information");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Seat Number:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Subject Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Student Code:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Subject Teacher:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtSC.setEditable(false);
        txtSC.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(txtSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 280, -1));

        txtSN.setEditable(false);
        txtSN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(txtSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 280, -1));

        txtSeatNumber.setEditable(false);
        txtSeatNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(txtSeatNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 280, -1));

        txtST.setEditable(false);
        txtST.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(txtST, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
            String b = null,c=null,d=null,f=null;
                               
     FileReader fr ;
        BufferedReader br;
        
        try{
            fr = new FileReader("C:\\datab\\data3.txt");
            br = new BufferedReader(fr);
            c=br.readLine();        
           
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        try{
            fr = new FileReader("C:\\datab\\data2.txt");
            br = new BufferedReader(fr);
            d=br.readLine();        
           
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        txtSC.setText(c);
         String sql;
        try{
          
                sql = "Select * from Dbk where Scode = '"+c+"'";
                  Statement st = con.createStatement();
              pst = con.prepareStatement(sql);
           rs = pst.executeQuery();
           pst.execute();
           if(rs.next()){
                txtSN.setText(rs.getString(2));
                txtST.setText(rs.getString(3));
                pst.close();
                b = rs.getString(2);
                 f = rs.getString(3);
           }
                
        }
                  catch(Exception e){
                        JOptionPane.showConfirmDialog(null, e);
                    }
         try{
          
                sql = "Select * from Dbtable where fname = '"+d+"' and teacher = '"+f+"' and stitle = '"+b+"'";
                  Statement st = con.createStatement();
              pst = con.prepareStatement(sql);
           rs = pst.executeQuery();
           pst.execute();
           if(rs.next()){
                txtSeatNumber.setText(rs.getString(6));
                pst.close();
                b = rs.getString(2);
           }else{
               txtSeatNumber.setText("Not enrolled in this subject!");
           }
                
        }
                  catch(Exception e){
                        JOptionPane.showConfirmDialog(null, e);
                    }
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSC;
    private javax.swing.JTextField txtSN;
    private javax.swing.JTextField txtST;
    private javax.swing.JTextField txtSeatNumber;
    // End of variables declaration//GEN-END:variables
}
